apiVersion: v1
kind: Service
metadata:
  name: micro-calc-service
  namespace: micro-calc
spec:
  type: ClusterIP
  selector:
    app: micro-calc
  ports:
    - name: http
      port: 8090
      targetPort: 8080
